-- insert 1
INSERT INTO CUSTOMERS(id, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, SERVISE_REQUEST_id)
VALUES(001,'Liza', 'Smith', 'smith@example.com', '000-00-1', 1), 
(002, 'Emma', 'Jonson', 'jonson@example.com', '000-00-2', 2),
(003, 'Michael', 'Williams', 'williams@example.com', '000-00-3', 3),
(004, 'Sophia', 'JOnes', 'jones@example.com', '000-00-4', 4);
-- insert 2
INSERT INTO SHOP(id, NAME, PHONE, EMAIL, ADDRESS, OPEN_HOURS)
VALUES(5001, 'Central Mobile Shop', '500-00-1', 'central@example.com', 'Pirosmani str 123', '24/7'),
(5002, 'North Mobile Shop', '500-00-2', 'north@example.com', 'pharnavazi str 10', '24/7'),
(5003, 'WEST Mobile Shop', '500-00-3', 'west@example.com', 'chavchavadze str  13', '24/7');
-- insert 3
INSERT INTO SERVICE_CENTERS(id, NAME, PHONE, EMAIL, ADDRESS, OPEN_HOURS)
VALUES(6001, 'Central Mobile Service', '600-00-1', 'centralService@example.com', 'Pirosnami str 10', '7/7'),
(6002, 'North Mobile Service', '600-00-2', 'northService@example.com', 'abuseridze str 10', '7/7'),
(6003, 'WEST Mobile Service', '600-00-3', 'westService@example.com', 'Pirosnami str 10', '7/7');
-- insert 4
INSERT INTO PHONES(id, BRAND, MODEL, RELEASE_DATE, PHONE_DETAIL, CUSTOMER_id, WARRANTIES_id, SERVICE_REQUESTS_id)
VALUES(666, 'APPLE', 'IPHONE 12 PRO MAX', '2020-10-13', '6.1-inch OLED display, triple-camera system', 001, 009, 007),
(667, 'SAMSUNG', 'Galaxy S21 Ultra', '2021-01-143', '6.8-inch AMOLED display, quad-camera system', 002, 010, 008);
-- insert 5
INSERT INTO PHONE_DETAILS(id, COLOR, BATTERY, PRICE, PHONE_id)
VALUES(190, 'grey','built-in rechargeable lithium-ion battery', '1200', 666);
-- insert 6
INSERT INTO DELIVERIES(id, SHOP_id, CUSTOMER_id, PHONE_id, DELIVERY_ADDRESS, OWNER_NAME, MOBILE_NUMBER, DELIVERY_STATUS)
VALUES(701, 5001, 001, '666', '456 Park Avenue, Anycity USA', 'John Doe', '456-45-33', true ),
(702, 5002, 002, '667', '789 Elm Street, Anyville USA', 'Bob Jonson', '456-45-33', false); 
-- insert 7
INSERT INTO SERVICE_HISTORY(id, PHONE_id, SERVICE_CENTER_id, SERVICE_TYPE, CUSTOMER_id)
VALUES(1001, 666, 601, 'Battery Replacemen', 901),
(802, 667, 602, 'Software Update', 902);
-- insert 8
INSERT INTO SERVICE_REQUESTS(id, CUSTOMER_id, PHONE_id, REQUESTED_SERVICE, SERVICE_CENTERS_id)
VALUES(801, 903, 666, 'Battery Replacemen', 6001 );
-- insert 9
INSERT INTO INVENTORY(id, SHOP_id, PHONE_id, QUANTITY)
VALUES(901, 5001, 666, 129),
(902, 5002, 667, 120);
-- insert 10
INSERT INTO WARRANTIES(id, PHONE_id, STRAT_DATE, END_DATE, WARRANTIES)
VALUES(1001, 666, 12-12-2022, 12-12-2023, '2-year manufacturer warranty');
-- insert 11
INSERT INTO PURCHASES(id, CUSTOMER_id, PHONE_id, PURCHASE_DATE, PURCHASE_PRICE)
VALUES(01, 003, 667, '12-02-2023', 1200);

-- update 10 examlpe
UPDATE WARRANTIES SET PHONE_id= 667 WHERE id=1001;
UPDATE INVENTORY SET QUANTITY='140' WHERE id=901;
UPDATE SERVICE_REQUESTS SET REQUESTED_SERVICE='Update Software' WHERE id=801;
UPDATE SERVICE_HISTORY SET SERVICE_TYPE='Update Software' WHERE id=1001;
UPDATE DELIVERIES SET DELIVERY_STATUS= true WHERE id =701;
UPDATE PHONE_DETAILS SET COLOR='PINK' WHERE id=190;
UPDATE PHONES SET CUSTOMER_id=003 WHERE id=666;
UPDATE SERVICE_CENTERS SET ADDRESS='Pirosmani str 89' WHERE id=6001;
UPDATE SHOP SET EMAIL='central1@example.com' WHERE id=5001;
UPDATE CUSTOMERS SET LAST_NAME="Rodrigues" WHERE id=004;

-- delete 10 example
DELETE FROM WARRANTIES WHERE id= 1001;
DELETE FROM INVENTORY WHERE QUANTITY=120;
DELETE FROM SERVICE_REQUESTS WHERE SERVICE_CENTERS_id=6001;
DELETE FROM SERVICE_HISTORY WHERE SERVICE_TYPE='Battery Replacemen';
DELETE FROM DELIVERIES WHERE OWNER_NAME='Bob Jonson';
DELETE FROM PHONE_DETAILS WHERE COLOR='PINK';
DELETE FROM PHONES WHERE BRAND='SAMSUNG';
DELETE FROM SERVICE_CENTERS WHERE EMAIL="westService@example.com";
DELETE FROM SHOP WHERE NAME='WEST Mobile Shop';
DELETE FROM CUSTOMERS WHERE id=004;

-- 5 example alter table 
ALTER TABLE DELIVERIES 
ADD DELIVERY_DATE DATE;

ALTER TABLE DELIVERIES 
ADD ONLY_FOR_DELETING INT;

ALTER TABLE DELIVERIES
MODIFY COLUMN  DELIVERY_STATUS VARCHAR(45) NOT NULL;

ALTER TABLE DELIVERIES
MODIFY COLUMN ONLY_FOR_DELETING VARCHAR(30);

ALTER TABLE INVENTORY
DROP COLUMN ONLY_FOR_DELETING;

ALTER TABLE SERVICE_REQUESTS 
ADD N INT;

ALTER TABLE SERVICE_REQUESTS
DROP COLUMN N;

-- agregat functions example
SELECT MAX(QUANTITY) FROM INVENTORY GROUP BY SHOP_id;
SELECT SUM(PURCHASE_PRICE) FROM PURCHASES GROUP BY CUSTOMER_id;
SELECT * FROM SERVICE_REQUESTS GROUP BY CUSTOMER_id, `REQUESTED_SERVICE` HAVING `SERVICE_CENTERS_id` = 6001 ;
SELECT COUNT(DISTINCT FIRST_NAME) FROM CUSTOMERS GROUP BY ADDRESS;
SELECT `PHONE_id`,`SERVICE_TYPE` FROM SERVICE_HISTORY GROUP BY `PHONE_id`,`SERVICE_TYPE`;

-- 1 big statement to join all tables in the database.
SELECT * FROM CUSTOMERS 
JOIN DELIVERIES ON CUSTOMERS.id = DELIVERIES.id
JOIN INVENTORY ON DELIVERIES.id=INVENTORY.id
JOIN PHONE_DETAILS ON INVENTORY.id=PHONE_DETAILS.id
JOIN PHONES ON PHONE_DETAILS.id=PHONES.id
JOIN PURCHASES ON PHONES.id=PURCHASES.id
JOIN SERVICE_CENTERS ON PURCHASES.id=SERVICE_CENTERS.id
JOIN SERVICE_HISTORY ON SERVICE_CENTERS.id=SERVICE_HISTORY.id
JOIN SERVICE_REQUESTS ON SERVICE_HISTORY.id=SERVICE_REQUESTS.id
JOIN SHOP ON SERVICE_REQUESTS.id=SHOP.id
JOIN WARRANTIES ON SHOP.id=WARRANTIES.id;

-- 5 statements with left, right, inner, outer joins.

SELECT * FROM SERVICE_REQUESTS 
INNER JOIN SERVICE_CENTER_EMPLOYESS
ON SERVICE_REQUESTS.id=SERVICE_CENTER_EMPLOYESS.id;

SELECT * FROM PHONES 
LEFT JOIN PHONE_DETAILS
ON PHONES.id=PHONE_DETAILS.id;

SELECT * FROM INVENTORY 
RIGHT JOIN SHOPS
ON INVENTORY.id=SHOPS.id;

SELECT * FROM CUSTOMERS 
FULL OUTER JOIN SERVICE_REQUESTS
ON CUSTOMERS.id=SERVICE_REQUESTS.id;

SELECT * FROM DELIVERIES 
INNER JOIN CUSTOMERS
ON DELIVERIES.id=CUSTOMERS.id;


